name: Daily arXiv Papers Summary

on:
  schedule:
    - cron: '0 1 * * *' # Chạy lúc 1:00 UTC, tức 8:00 sáng giờ Việt Nam
  workflow_dispatch: # Thêm để chạy thủ công nếu cần

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt

    - name: Run Python script
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_ACTIONS: "true" # Biến này giúp code biết đang chạy trên GitHub
      run: |
        python run.py "http://export.arxiv.org/api/query" "cat:cs.AI" "submittedDate" "descending" "10"
